server:
  port: 10001

spring:
  application:
    name: appserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:10001/eureka

logging:
  level:
    com:
      example:
        demo: debug