server:
  port: 10003

spring:
  application:
    name: eurekaconsumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
    